### PR TITLE
Kh 1.8 edits

### PR DESCRIPTION
**Pull request by khuang-pivotal**

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @khuang-pivotal !

**Comment by bentarnoff** [comment]
Hey @khuang-pivotal do these need to go to PWS?

**Comment by khuang-pivotal** [comment]
@bentarnoff yes, these will need to go to PWS when 1.8 goes live.

**Comment by bentarnoff** [comment]
Great, thanks @khuang-pivotal

**Pull request merged**
