### PR TITLE
Correct instructions on using API to configure SSO Service plan [#165…

### PR DESCRIPTION
**Pull request by peterhaochen47**
…362305]

Related story: https://www.pivotaltracker.com/story/show/165362305
Please reach out to us if you have any questions. Once merged, we can start backporting this fix to 1.8, 1.7.

### CODE REVIEW

**Comment by peterhaochen47** [comment]
Docs team: In the past we had the PM review the PR. But since we soon won't have a PM for a while, please review it on your part & reach out to us (#pcf-app-sso slack) if you have any questions.

**Comment by radaeze** [comment]
@peterhaochen47 That makes sense! Will merge now. Thanks!

**Comment by jncd** [comment]
Hi @peterhaochen47 and @radaeze 
You two make a fine team. This PR looks really good and is now in three versions of the doc:

- http://docs-pcf-staging.cfapps.io//p-identity/1-n/manage-service-plans-api.html#updating
- http://docs-pcf-staging.cfapps.io//p-identity/1-8/manage-service-plans-api.html#updating
- http://docs-pcf-staging.cfapps.io//p-identity/1-7/manage-service-plans-api.html#updating

Should we make the 1.7 and 1.8 versions live on docs.pivotal.io?

**Comment by peterhaochen47** [comment]
Hello @jncd & @radaeze, thanks haha :)

FYI The staging docs for 1.8 and 1.7 are still saying:
```
Run the following command, directing the output to a text file: 
uaac curl -k /identity-zones/ZONE-ADMIN-CLIENT-ID > JSON-BLOB.txt
```

But the 1-n staging docs is correct:
```
Run the following command, directing the output to a text file: 
uaac curl -k /identity-zones/YOUR-IDENTITY-ZONE-ID > JSON-BLOB.txt
```

**Pull request merged**
