### PR TITLE
Added documentation for configuring SSO with single subnet networks.

### PR DESCRIPTION
**Pull request by khuang-pivotal**

### CODE REVIEW

**Comment by ljarzynski** [comment]
Docs team: find out if these changes need to be made to the master-pws branch as well, if so cherry-pick them.

**Comment by ljarzynski** [comment]
Thanks, @khuang-pivotal !

**Comment by ljarzynski** [comment]
@khuang-pivotal Should I bring this to 1.8 as well?

**Comment by khuang-pivotal** [comment]
@ljarzynski Yes, please.

**Pull request merged**
