### PR TITLE
Kh 1.8 edits

### PR DESCRIPTION
**Pull request by khuang-pivotal**

### CODE REVIEW

**Comment by ljarzynski** [comment]
Docs team: find out if these changes need to be made to the master-pws branch as well, if so cherry-pick them.

**Comment by ljarzynski** [comment]
@khuang-pivotal just double-checking because of the name of your branch- Is this ready to be merged or should we hold off?

**Comment by khuang-pivotal** [comment]
@ljarzynski. This is the latest I have for 1.8. I suspect there will be minor changes, but no more major changes for this release.

**Comment by ljarzynski** [comment]
Brought the commits into the 1.8 branch instead of master: https://github.com/pivotal-cf/docs-identity/commit/b86100f891b749a68d0562abaf3db86f49db9d6a. Will close out this PR.

**Pull request closed without merging**
