### PR TITLE
Mention Services Key are only for SSO 1.7.0+ [#160857026]

### PR DESCRIPTION
**Pull request by pydctw**
Signed-off-by: Peter Chen <pchen@pivotal.io>

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @pydctw !

**Comment by jncd** [comment]
Hi @pydctw Winnie and Peter. Are you in the office today? I want to swing by and ask you about this PR. This doc is only for v1.7.0 and later — so this note shouldn't be necessary. Have customers reported confusion?

**Comment by tnwang** [comment]
@jncd Yes, customers were attempting to use the command on version 1.5 even though it was only for version 1.7.

**Comment by jncd** [comment]
@tnwang and @pydctw Thanks for the clarification. [sigh] 
Given the circumstances, would it help to be even more specific by saying this: 

> The service key feature was introduced in v1.7. If you are using v1.6 or earlier, select that documentation version from the dropdown at the top of this page.

**Comment by tnwang** [comment]
Possibly - I'm not sure how familiar customers are with actually using the version feature of our docs.

Since the instructions are the same across versions except for the new features, I was planning to have our team add version notes for the newer features (new story for another feature here https://www.pivotaltracker.com/story/show/161228849).

**Pull request merged**
