### PR TITLE
Improve saml integration docs

### PR DESCRIPTION
**Pull request by peterhaochen47**
Story: https://www.pivotaltracker.com/story/show/164124956
Misc improvements on the SAML IDP integration steps.

### CODE REVIEW

**Comment by peterhaochen47** [comment]
Please reach out if you need help reviewing this PR.

**Comment by RichardJJG** [comment]
Thanks, @peterhaochen47.

**Comment by peterhaochen47** [comment]
@RichardJJG This is a general improvement and not specific to SSO 1.9, so putting this on other branches (1.7 and 1.8) would be good.

**Comment by RichardJJG** [comment]
@peterhaochen47, thanks, will do.

**Pull request merged**
