### PR TITLE
Add docs for 1.10, which includes Web + Service to Service

### PR DESCRIPTION
**Pull request by adidner**
grant type.

This commit adds a page, web-service-to-service-app.html,
that should be linked to via the sidebar, which is in a
separate repo (docs-book-identity).

Story Link: https://www.pivotaltracker.com/story/show/167056511

[#167056511]

Signed-off-by: Aaron Didner <adidner@pivotal.io>

### CODE REVIEW

**Comment by adidner** [comment]
Feel free to reach out to use with questions or desires to pair. 

Also this commit adds a page, web-service-to-service-app.html,
that should be linked to via the sidebar, which is in a
separate repo (docs-book-identity). It is unclear how we are suppose to achieve this and we were wondering if the docs team could do this for us.

**Comment by jncd** [comment]
Hi @adidner 
Thanks! I'm merging now. 
Where in the subnav, do you think it should go? (I'm happy to do the work to place it.)
(We might wait until Ramia is back next week to work with you on the edits. She knows this book best.)
jane

**Comment by adidner** [comment]
Screen Shot 2019-08-15 at 12 02 45 PM
 As shown here it would be titled "Web + Service-to-Service" and it would be the last entry under the "App Types" heading.
Also waiting is fine. Thanks for the quick response

**Comment by jncd** [comment]
@adidner Thanks so much for exact position of the new page. It's on the subnav now: http://docs-pcf-staging.cfapps.io/p-identity/1-n/configure-apps/web-service-to-service-app.html (creds=pivotalcf/wilderror16)

**Pull request merged**
