### PR TITLE
Kh master ping federate edits

### PR DESCRIPTION
**Pull request by khuang-pivotal**

### CODE REVIEW

**Comment by ljarzynski** [comment]
@khuang-pivotal just to check, do we want to bring the PingOne and Ping Federate integration guides to master-pws as well? If so, I can do that.

**Comment by khuang-pivotal** [comment]
@ljarzynski Yes, let's merge this to master-pws as well. Thanks.

**Comment by ljarzynski** [comment]
@khuang-pivotal sounds good! I think I might write a tool that comments on PRs to the master branch of this repo to remind us to check and see if we need to also cherry-pick to master pws.

**Comment by ljarzynski** [comment]
Thanks, @khuang-pivotal!

**Pull request merged**
